/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelreservation;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.lang.String;
import java.sql.PreparedStatement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author florm
 */
public class CustomerDetails extends javax.swing.JFrame {

    private ArrayList<CustomerDetails> aList;
    private String first_name, last_name, email, mobile;
    private int room, count;

    /**
     * Creates new form CustomerDetails
     */
    

    public CustomerDetails() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in the screen

        aList = new ArrayList<>();

        first_name = new String();
        last_name = new String();
        email = new String();
        mobile = new String();
        room = 0;
        count = 0;
        
    }

    public static void writeToFile(ArrayList<String> list, String search) {
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("reservation.txt"));
            for (String x : list) {
                writer.write(x);
                writer.newLine();
            }
            writer.close();
        } catch (Exception e) {
            e.getStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        table = new javax.swing.JPanel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelMobile = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        emailTf = new javax.swing.JTextField();
        roomTf = new javax.swing.JTextField();
        lastTf = new javax.swing.JTextField();
        mobileTf = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabelFirstName1 = new javax.swing.JLabel();
        firstTf = new javax.swing.JTextField();
        jButtonClean = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelFirstName2 = new javax.swing.JLabel();
        typeTf = new javax.swing.JTextField();
        jButtonImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(68, 108, 179));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER DETAILS");

        jLabelMin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("x");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(275, 275, 275)
                .addComponent(jLabelMin)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClose)
                        .addComponent(jLabelMin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        table.setBackground(new java.awt.Color(44, 62, 80));

        jLabelFirstName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFirstName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFirstName.setText("First Name:");

        jLabelLastName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLastName.setText("Last Name:");

        jLabelMobile.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelMobile.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMobile.setText("Mobile:");

        jLabelEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email:");

        emailTf.setBackground(new java.awt.Color(108, 122, 137));
        emailTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTfActionPerformed(evt);
            }
        });

        roomTf.setBackground(new java.awt.Color(108, 122, 137));

        lastTf.setBackground(new java.awt.Color(108, 122, 137));

        mobileTf.setBackground(new java.awt.Color(108, 122, 137));

        jButtonRegister.setText("Register");
        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseClicked(evt);
            }
        });
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room", "First Name", "Last Name", "Mobile", "Email"
            }
        )
        //make the jtable cells not editable
        {public boolean isCellEditable (int row, int column){return false;}}
    );
    jTable.setSelectionBackground(new java.awt.Color(153, 153, 255));
    jTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable);

    jLabelFirstName1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    jLabelFirstName1.setForeground(new java.awt.Color(255, 255, 255));
    jLabelFirstName1.setText("Room:");

    firstTf.setBackground(new java.awt.Color(108, 122, 137));

    jButtonClean.setText("Clean");
    jButtonClean.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonCleanActionPerformed(evt);
        }
    });

    jButtonEdit.setText("Edit");
    jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditActionPerformed(evt);
        }
    });

    jButtonDelete.setText("Delete");
    jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonDeleteActionPerformed(evt);
        }
    });

    jLabelFirstName2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    jLabelFirstName2.setForeground(new java.awt.Color(255, 255, 255));
    jLabelFirstName2.setText("Type:");

    typeTf.setBackground(new java.awt.Color(108, 122, 137));

    jButtonImport.setText("Import Data");
    jButtonImport.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonImportActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
    table.setLayout(tableLayout);
    tableLayout.setHorizontalGroup(
        tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(tableLayout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(tableLayout.createSequentialGroup()
                    .addComponent(jLabelFirstName1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(roomTf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(jLabelFirstName2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(typeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(51, 51, 51))
                .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableLayout.createSequentialGroup()
                        .addComponent(jLabelFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstTf, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tableLayout.createSequentialGroup()
                        .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMobile)
                            .addComponent(jLabelLastName)
                            .addComponent(jLabelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastTf, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobileTf, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tableLayout.createSequentialGroup()
                                .addComponent(jButtonRegister)
                                .addGap(73, 73, 73)
                                .addComponent(jButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonClean))))))
            .addGap(27, 27, 27)
            .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tableLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jButtonImport, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(53, 53, 53)
                    .addComponent(jButtonDelete))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(20, Short.MAX_VALUE))
    );
    tableLayout.setVerticalGroup(
        tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableLayout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tableLayout.createSequentialGroup()
                    .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(roomTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFirstName1)
                        .addComponent(jLabelFirstName2)
                        .addComponent(typeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFirstName)
                        .addComponent(firstTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLastName)
                        .addComponent(lastTf))
                    .addGap(18, 18, 18)
                    .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMobile)
                        .addComponent(mobileTf))
                    .addGap(18, 18, 18)
                    .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEmail)
                        .addComponent(emailTf)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGap(33, 33, 33)
            .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonRegister)
                .addComponent(jButtonEdit)
                .addComponent(jButtonClean)
                .addComponent(jButtonDelete)
                .addComponent(jButtonImport))
            .addGap(24, 24, 24))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        
        if (firstTf.getText().equals("") || lastTf.getText().equals("") || mobileTf.getText().equals("")
                || emailTf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter with some data");
        } else {
            

            //get data from fields

            String first_name = firstTf.getText();
            String last_name = lastTf.getText();
            String mobile = mobileTf.getText();
            String email = emailTf.getText();
           
            CustomerDetails cd = new CustomerDetails();
            aList = new ArrayList<>();
            
           cd.setName(first_name);
           
            aList.add(cd);
            count++;
            
            try {
                String str[] = null;
            } catch (Exception e) {
            }
            
            File outFile;
            FileWriter fw;
            BufferedWriter bw;
            
           
//
//            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//               
//            dateChooser_In.setText(date);
//
//            dateChooser_Out.setText(date);
//
//            CustomerDetails cd;
//            cd = new CustomerDetails();
//
 
            try {
                outFile = new File("reservation.txt");
                fw = new FileWriter(outFile, true);
                bw = new BufferedWriter(fw);
                
                bw.write(first_name + " " + "/");
                bw.write(last_name + " " + "/");
                bw.write(mobile + " " + "/");
                bw.write(email + " " + "/");
                bw.newLine();
                
                bw.close();
//                bw.write(stColumn[1]first_name + "\\s");
//
//                bw.write(stLine[2]last_name + "\\s");
//
//                bw.write(stLine[3]mobile + "");
//
//                bw.write(stLine[4]email + "");
                
                
                
                
                JOptionPane.showMessageDialog(null, "Data Inserted Successfully!");

                //Limpeza dos campos de entrada
                firstTf.setText("");
                lastTf.setText("");
                mobileTf.setText("");
                emailTf.setText("");

            } catch (IOException e) {
                System.out.println("Error writing file: " + e);
            }

        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonRegisterMouseClicked

    private void emailTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTfActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // get jtable model 
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();

        //get the selected row
        int selectedRowIndex = jTable.getSelectedRow();

        //display data
        roomTf.setText(model.getValueAt(selectedRowIndex, 0).toString());
        firstTf.setText(model.getValueAt(selectedRowIndex, 1).toString());
        lastTf.setText(model.getValueAt(selectedRowIndex, 2).toString());
        mobileTf.setText(model.getValueAt(selectedRowIndex, 3).toString());
        emailTf.setText(model.getValueAt(selectedRowIndex, 4).toString());
    }//GEN-LAST:event_jTableMouseClicked

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed

// clean the fields
        roomTf.setText("");
        firstTf.setText("");
        lastTf.setText("");
        mobileTf.setText("");
        emailTf.setText("");
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // edit the selected from jtable
        
        int i = jTable.getSelectedRow();
        
        DefaultTableModel m = (DefaultTableModel)jTable.getModel();
        if(i>=0){
            m.setValueAt(roomTf.getText(), i, 0);
            m.setValueAt(firstTf.getText(), i, 1);
            m.setValueAt(lastTf.getText(), i, 2);
            m.setValueAt(mobileTf.getText(), i, 3);
            m.setValueAt(emailTf.getText(), i, 4);
        }else{
            JOptionPane.showMessageDialog(null,"Error");
        }

       
    
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
//clear the jtable
//        jTable.setModel(new DefaultTableModel(null, new Object[]{"room", "first_name", "last_name", "mobile", "email"}));

//delete selected from jtable
int getSelectedRowForDeletation = jTable.getSelectedRow();
DefaultTableModel m = (DefaultTableModel)jTable.getModel();
//check if some row is selected
if(getSelectedRowForDeletation >=0){
    m.removeRow(getSelectedRowForDeletation);
    JOptionPane.showMessageDialog(null,"Data Deleted" );
}else{
    JOptionPane.showMessageDialog(null, "No data selected");
}
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
        // import data from text file

        String filePath = "C:\\Users\\florm\\Documents\\NetBeansProjects\\HotelReservation\\reservation.txt";
        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));

            String firstLine = br.readLine().trim();//get the first line
            String[] columnName = firstLine.split(",");//get the columns name from the first line
            DefaultTableModel dtm = (DefaultTableModel) jTable.getModel();//set columns name to the jtable 
            dtm.setColumnIdentifiers(columnName);

            Object[] tableLine = br.lines().toArray();//get line from text file
            //take data from line and set data to jtable
            for (int i = 0; i < tableLine.length; i++) {
                String line = tableLine[i].toString().trim();
                String[] dataRow = line.split("/");
                dtm.addRow(dataRow);
            }

        } catch (Exception ex) {
            Logger.getLogger(CustomerDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTf;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField firstTf;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelFirstName1;
    private javax.swing.JLabel jLabelFirstName2;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelMobile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField lastTf;
    private javax.swing.JTextField mobileTf;
    private javax.swing.JTextField roomTf;
    private javax.swing.JPanel table;
    private javax.swing.JTextField typeTf;
    // End of variables declaration//GEN-END:variables

}
